.TH gearman_client_clone 3 2010-06-30 "Gearman" "Gearman"
.SH NAME
gearman_client_clone \- Client Declarations
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI " gearman_client_st *gearman_client_clone(gearman_client_st " *client ",  const gearman_client_st *from);"
.SH DESCRIPTION
Clone a client structure.
*
.SH PARAMETERS
.TP
.BR 
[in] client Caller allocated structure, or NULL to allocate one.
.TP
.BR 
[in] from Structure to use as a source to clone from.
.SH "RETURN VALUE"
Same return as gearman_client_create().
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
