.TH gearman_client_remove_options 3 2010-06-30 "Gearman" "Gearman"
.SH NAME
gearman_client_remove_options \- Client Declarations
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI " void gearman_client_remove_options(gearman_client_st " *client ",  gearman_client_options_t options);"
.SH DESCRIPTION
Remove options for a client structure.
*
.SH PARAMETERS
.TP
.BR 
[in] client Structure previously initialized with
gearman_client_create() or gearman_client_clone().
.TP
.BR 
[in] options Available options for client structures.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
