.TH gearman_worker_create 3 2010-06-30 "Gearman" "Gearman"
.SH NAME
gearman_worker_create \- Worker Declarations
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI " gearman_worker_st *gearman_worker_create(gearman_worker_st *worker);"
.SH DESCRIPTION
Initialize a worker structure. Always check the return value even if passing
in a pre-allocated structure. Some other initialization may have failed. It
is not required to memset() a structure before providing it.
*
.SH PARAMETERS
.TP
.BR 
[in] worker Caller allocated structure, or NULL to allocate one.
.SH "RETURN VALUE"
On success, a pointer to the (possibly allocated) structure. On
failure this will be NULL.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
